package com.wizzdi.examples.runtime.api.response;

public enum CaptureStatusDetailsReason {
  BUYER_COMPLAINT,

  CHARGEBACK,

  ECHECK,

  INTERNATIONAL_WITHDRAWAL,

  OTHER,

  PENDING_REVIEW,

  RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION,

  REFUNDED,

  TRANSACTION_APPROVED_AWAITING_FUNDING,

  UNILATERAL,

  VERIFICATION_REQUIRED
}
