package com.wizzdi.examples.runtime.api.request;

public enum EciFlag {
  MASTERCARD_NON_3D_SECURE_TRANSACTION,

  MASTERCARD_ATTEMPTED_AUTHENTICATION_TRANSACTION,

  MASTERCARD_FULLY_AUTHENTICATED_TRANSACTION,

  FULLY_AUTHENTICATED_TRANSACTION,

  ATTEMPTED_AUTHENTICATION_TRANSACTION,

  NON_3D_SECURE_TRANSACTION
}
